<?php
/**
 *
 * @category   Webinterpret
 * @package    Webinterpret_Connector
 * @author     Webinterpret Team <info@webinterpret.com>
 * @license    http://opensource.org/licenses/osl-3.0.php
 */
?>
<?php if (Mage::helper('webinterpret_connector')->isEnabled()): ?>
<!-- webinterpret_head -->
<?php echo $this->getHeadHtml(); ?>
<script type="text/javascript" src="<?php echo $this->getLoaderUrl(); ?>"></script>
<!-- end webinterpret_head -->
<?php endif; ?>
