<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita645de5498819440995422a042fbf08c
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'MaxMind\\' => 8,
        ),
        'G' => 
        array (
            'GeoIp2\\' => 7,
        ),
        'C' => 
        array (
            'Composer\\CaBundle\\' => 18,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'MaxMind\\' => 
        array (
            0 => __DIR__ . '/..' . '/maxmind/web-service-common/src',
        ),
        'GeoIp2\\' => 
        array (
            0 => __DIR__ . '/..' . '/geoip2/geoip2/src',
        ),
        'Composer\\CaBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/composer/ca-bundle/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'M' => 
        array (
            'MaxMind' => 
            array (
                0 => __DIR__ . '/..' . '/maxmind-db/reader/src',
            ),
        ),
        'B' => 
        array (
            'Buzz' => 
            array (
                0 => __DIR__ . '/..' . '/kriswallsmith/buzz/lib',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita645de5498819440995422a042fbf08c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita645de5498819440995422a042fbf08c::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInita645de5498819440995422a042fbf08c::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
